version: '3.8'

services:
  php:
    container_name: coffreo_backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    working_dir: /var/www
    networks:
      - app_network

  nginx:
    container_name: coffreo_server
    image: nginx:latest
    volumes:
      - ./backend:/var/www
      - ./docker/backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - app_network
    depends_on:
      - php

  postgres:
    image: postgres:latest
    container_name: coffreo_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app_network

  frontend:
    container_name: coffreo_frontend
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - app_network
    depends_on:
      - php

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
