version: '3.8'

services:
  php:
    container_name: coffreo_backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    working_dir: /var/www
    networks:
      - app_network

  nginx:
    container_name: coffreo_server
    image: nginx:latest
    volumes:
      - ./backend:/var/www
      - ./docker/backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - app_network
    depends_on:
      - php

  frontend:
    container_name: coffreo_frontend
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - app_network
    depends_on:
      - php

networks:
  app_network:
    driver: bridge
