version: '3.8'

services:
  php:
    container_name: coffreo_api
    build:
      context: ./docker
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    networks:
      - app_network

  nginx:
    container_name: coffreo_server
    image: nginx:latest
    volumes:
      - ./backend:/var/www
      - ./docker/backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - app_network
    depends_on:
      - php

networks:
  app_network:
    driver: bridge
